<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="L4_kolejiste_ST" Id="{ac1ef4e9-930c-4995-8d5f-2e5246b680cd}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK L4_kolejiste_ST
VAR_INPUT
	PRE_I, PRE_KLA: BOOL;	// Poloha I přepínače (1 = přep. v poloze I)
	PRE_II, PRE_OPA: BOOL;	// Poloha II přepínače (1 = přep. v poloze II)
	HRA_LEV, SP1: BOOL;		// Levé hradlo (1 = přítomno vozidlo)
	HRA_ZAV, SP2: BOOL;		// Hradlo závor (1 = přítomno vozidlo)
END_VAR
VAR_OUTPUT
	ZAVORY, Z: BOOL;		// Stahování závor (1 = závory staženy)
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="L4_kolejiste_ST">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>